### Get user favorites
GET http://localhost:4041/api/v1/users/user/favorites HTTP/1.1
Host: localhost:4041
Accept: application/json
Cookie: session_id=29eb95aa-a7f7-4ede-b830-f29ba83d28b9

###

### Update user favorites (replace with valid video IDs)
POST http://localhost:4041/api/v1/users/user/favorites HTTP/1.1
Host: localhost:4041
Content-Type: application/json
Accept: application/json
Cookie: session_id=29eb95aa-a7f7-4ede-b830-f29ba83d28b9

{
  "favorites": [
    "5fe0c0f695bbb3e575b4ce215985c6982702b6d028e2d2db21ef72f4bcabe0df"
  ]
}
