###
# Get tags for a specific video
GET http://127.0.0.1:8080/api/v1/videos/tags/087be485e0acad6fb1ba026e75542fed5f52e073496c649bc4a3ce345a63f48f HTTP/1.1
Host: 127.0.0.1:8080
Accept: application/json

###
# Update tags for a specific video
POST http://127.0.0.1:8080/api/v1/videos/tags/087be485e0acad6fb1ba026e75542fed5f52e073496c649bc4a3ce345a63f48f HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/json
Accept: application/json

{
  "tags": ["action", "funny", "short"]
}

###
# Invalid update (empty tags)
POST http://127.0.0.1:8080/api/v1/videos/tags/video123 HTTP/1.1
Host: 127.0.0.1:8080
Content-Type: application/json
Accept: application/json

{
  "tags": []
}
