@baseUrl = http://localhost:4040
@session_id = 953b7910-5f87-45ba-9244-df5dd98b28ba
@videoId = 3e73d4d3a2758baa59b6b8928bd6c3406c65582c99b24ff3474ae60f5e55c461
@folder = 

### Get Video Details by ID
GET {{baseUrl}}/api/v1/videos/{{videoId}}
Accept: application/json
Cookie: session_id={{session_id}}

###

### Get Videos by Folder
GET {{baseUrl}}/api/v1/videos?folder={{folder}}
Accept: application/json
Cookie: session_id={{session_id}}

###

### Get Folder List
GET {{baseUrl}}/api/v1/folders
Accept: application/json
Cookie: session_id={{session_id}}
