### Get Video Details by ID (replace videoId and session_id accordingly)
GET http://127.0.0.1:5050/api/v1/videos/3e73d4d3a2758baa59b6b8928bd6c3406c65582c99b24ff3474ae60f5e55c461
Accept: application/json

###

### Get Videos by Folder (replace folder path and session_id accordingly)
GET http://127.0.0.1:5050/api/v1/videos?folder=
Accept: application/json

### Get Folder List (replace session_id if needed)
GET http://127.0.0.1:5050/api/v1/folders
Accept: application/json
