@baseUrl = http://localhost:4040
@session_id = e9ef61b2-17cf-45fc-9ab8-e6ef97aae213
@videoId = d1e02ddf33872e49a6b8c7c60814ec6a851f5c2e7faf61c376b717da77a9ac37
@folder = 

### Get Video Details by ID
GET {{baseUrl}}/api/v1/videos/{{videoId}}
Accept: application/json
Cookie: session_id={{session_id}}

###

### Get Videos by Folder
GET {{baseUrl}}/api/v1/videos?folder={{folder}}
Accept: application/json
Cookie: session_id={{session_id}}

###

### Get Folder List
GET {{baseUrl}}/api/v1/folders
Accept: application/json
Cookie: session_id={{session_id}}

### Stream Video by ID (with Range header to request partial content)
GET {{baseUrl}}/api/v1/stream/{{videoId}}
Accept: video/mp4
Cookie: session_id={{session_id}}
Range: bytes=0-2000
