@baseUrl = http://localhost:4040
@session_id = 2c27df6b-bd3c-4d5e-b97c-6b17ae36766b
@videoId = d1e02ddf33872e49a6b8c7c60814ec6a851f5c2e7faf61c376b717da77a9ac37
@folder = 

### Get Video Details by ID
GET {{baseUrl}}/api/v1/videos/{{videoId}}
Accept: application/json
Cookie: session_id={{session_id}}

###

### Get Videos by Folder
GET {{baseUrl}}/api/v1/videos?folder={{folder}}
Accept: application/json
Cookie: session_id={{session_id}}

###

### Get Folder List
GET {{baseUrl}}/api/v1/folders
Accept: application/json
Cookie: session_id={{session_id}}

### Stream Video by ID (with Range header to request partial content)
GET {{baseUrl}}/api/v1/stream/{{videoId}}
Accept: video/mp4
Cookie: session_id={{session_id}}
Range: bytes=0-2000
